# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = CG_Scanline
DESTDIR = ../x64/Release
CONFIG += release
LIBS += -L"." \
    -l../GL/glut32
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(CG_Scanline.pri)
QT += opengl
CONFIG += console